version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn build:prod
      - deploy:
          name: Deply to Firebase
          command: yarn deploy -- --token "$FIREBASE_TOKEN"
